# Generated by Django 6.0.5 on 2026-05-24 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonorOutreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_rank_score', models.FloatField(default=0.0)),
                ('rank_position', models.IntegerField(default=0)),
                ('distance_km', models.FloatField(default=0.0)),
                ('vapi_call_id', models.CharField(blank=True, max_length=200)),
                ('call_status', models.CharField(choices=[('queued', 'Queued'), ('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('no_answer', 'No Answer'), ('declined', 'Declined'), ('accepted', 'Accepted'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('call_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('donor_response', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('ai_ranking_rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreaches', to='donors.donor')),
            ],
            options={
                'ordering': ['rank_position'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group_needed', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('units_needed', models.IntegerField(default=1)),
                ('urgency_level', models.CharField(choices=[('critical', 'Critical'), ('urgent', 'Urgent'), ('standard', 'Standard')], default='urgent', max_length=10)),
                ('patient_condition', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('donors_contacted', 'Donors Contacted'), ('donor_confirmed', 'Donor Confirmed'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('n8n_execution_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('donors_contacted', models.ManyToManyField(blank=True, through='emergency.DonorOutreach', to='donors.donor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='emergency.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='donoroutreach',
            name='emergency_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreaches', to='emergency.emergencyrequest'),
        ),
    ]
